[package]
name = "day10"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
z3 = { version = "0.19.6", features = ["gh-release"] }
